on: [push]

jobs:
  build-and-publish:
    permissions:
      packages: write
      contents: read

    runs-on: ubuntu-latest
    name: My workflow
    steps:
      - name: Execute Action Graph
        uses: actionforge/action@v0.9.42
        with:
          graph_file: workflow.yml
